services:
  postgresql:
    image: postgres:16.0-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: coffee
      POSTGRES_DB: coffee
      TZ: UTC
    healthcheck:
      test: pg_isready -U coffee -d coffee
      interval: 30s
      timeout: 20s
      retries: 10
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: local
      options:
        max-size: 10M

  smtp:
    image: marlonb/mailcrab:latest
    ports:
      - "1025:1025"
      - "8025:1080"
    restart: on-failure:10
    logging:
      driver: local
      options:
        max-size: 2M
